### ISSUE TITLE
More useful as a proxy?

### ISSUE THREAD

**Issue by ssoroka** [juanpabloaj/morgue#1]
Thanks for sharing this! 

I've been thinking about something like this for a while, but perhaps it would be more useful as part of a proxy service? 

I'm curious as to how you're using it.

**Comment by juanpabloaj** [comment]
You are welcome.

Sometimes, to test web services, I need to create simulators with http/json responses.

With this tool, I can create some json responses, upload to this tool, and I can use it as simulator for the tests.
